### ISSUE TITLE
consider probabilistic algs?

### ISSUE THREAD

**Issue by gkiar** [neurodata/checklists#27]
[algs.md](https://github.com/neurodata/checklists/blob/master/algorithms.md) is awesome.
one open question is how do I adapt this for probabilistic algs?

**Comment by jovo** [comment]
i looked through it again, i think it works for probabilistic algs.
i will make a matlab "livescript" example, and see how that goes...

**Comment by jovo** [comment]
re-open if you think there is clearly something i am missing.
