### ISSUE TITLE
algorithms.md feedback

### ISSUE THREAD

**Issue by jovo** [neurodata/checklists#33]
- [x] pull the pseudocode from [MGC](https://www.overleaf.com/read/ygghvtgftzpp), you made your own format, but better to use standard format if possible?
- [x]  p-value: you don't specific what your test statistic is.
- [x] "Summary plot" a histogram of what??
- [x] "5. Quantitative evaluation code per trial" doesn't implement the function you said, which permutes the labels based on their means?
- [x] i don't understand your quantitative analysis over all trials.  are you computing a p-value *per trial*?  how are you getting a single number out of that? or are you not?
- [x] you skipped a bunch of sections: real data, synthetic data, etc....??

more later.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/200834345695850/224288584413266)

**Comment by gkiar** [comment]
- I used the mgc alg, at some iteration of it, as my template, following it's format exactly. It looked very similar when it was in latex, but you asked for it in markdown, so it won't look the same.
- I did a permutation test and computed portion correct, what do you mean?
- I'll clarify is a histogram of performance (portion of labels correct).
- yes it is what I said? My quantitative evaluation is computing the portion correctly assigned, which the truth function does. I don't know where you interpreted that I would permute anything based on its mean? Even in the permutation test description i don't use means.
-  I'm computing average performance then getting a pvalue for it.
- ya, I don't have real data like this and this is the point that they need to work through to get it. I can do the rest but this is implementing their algorithm, the rest is applying it.

**Comment by jovo** [comment]
Ok. Please do the rest.
We want to know more about it which we will learn when you do it.

I'll explain the other stuff in person today
